name: deep-speaker
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.11.0
  - aiohttp=3.6.3
  - appdirs=1.4.4
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - backcall=0.2.0
  - black=19.10b0
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2020.12.8
  - cachetools=4.2.0
  - certifi=2020.12.5
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.1
  - cryptography=3.3.1
  - cycler=0.10.0
  - dbus=1.13.18
  - decorator=4.4.2
  - defusedxml=0.6.0
  - dill=0.3.1.1
  - entrypoints=0.3
  - expat=2.2.10
  - fontconfig=2.13.0
  - freetype=2.10.4
  - gast=0.2.2
  - glib=2.66.1
  - google-auth=1.24.0
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - grpcio=1.31.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.10.0
  - hdf5=1.10.6
  - icu=58.2
  - idna=2.10
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - iniconfig=1.1.1
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=5.6.4
  - jedi=0.17.0
  - jinja2=2.11.2
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - keras=2.3.1
  - keras-applications=1.0.8
  - keras-base=2.3.1
  - keras-preprocessing=1.1.0
  - kiwisolver=1.3.0
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - llvmlite=0.31.0
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - more-itertools=8.6.0
  - multidict=4.7.6
  - mypy_extensions=0.4.3
  - natsort=7.0.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - notebook=6.1.5
  - numba=0.48.0
  - numpy=1.18.5
  - numpy-base=1.18.5
  - oauthlib=3.1.0
  - openssl=1.1.1i
  - opt_einsum=3.1.0
  - packaging=20.8
  - pandas=1.0.3
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pathspec=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - pluggy=0.13.1
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.13.0.1
  - ptyprocess=0.6.0
  - py=1.10.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.7.3
  - pyjwt=1.7.1
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - pytest=6.2.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - pytz=2020.4
  - pyyaml=5.3.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.11.13
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scipy=1.5.2
  - send2trash=1.5.0
  - setuptools=51.0.0
  - sip=4.19.8
  - six=1.15.0
  - sqlite=3.33.0
  - tbb=2020.3
  - tensorboard=2.3.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.1.0
  - tensorflow-base=2.1.0
  - tensorflow-estimator=2.1.0
  - termcolor=1.1.0
  - terminado=0.9.1
  - testpath=0.4.4
  - tk=8.6.10
  - toml=0.10.1
  - tornado=6.1
  - tqdm=4.45.0
  - traitlets=5.0.5
  - typed-ast=1.4.1
  - typing_extensions=3.7.4.3
  - urllib3=1.26.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - pip:
    - audioread==2.1.9
    - joblib==1.0.0
    - librosa==0.7.2
    - python-speech-features==0.6
    - resampy==0.2.2
    - scikit-learn==0.23.2
    - soundfile==0.10.3.post1
    - threadpoolctl==2.1.0
